const PREFIX = 'HEADER'

export const FOCUS_SEARCH_INPUT = `${PREFIX}_FOCUS_SEARCH_INPUT`
export const BLUR_SEARCH_INPUT = `${PREFIX}_BLUR_SEARCH_INPUT`
export const CHANGE_SEARCH_LIST = `${PREFIX}_CHANGE_SEARCH_LIST`
export const MOUSE_ENTER = `${PREFIX}_MOUSE_ENTER`
export const MOUSE_LEAVE = `${PREFIX}_MOUSE_LEAVE`
export const CHANGE_SEARCH_PAGE = `${PREFIX}_CHANGE_SEARCH_PAGE`
